[package]
name = "portal-updater"
version = "0.1.0"
authors = ["Marco Napetti <marco.napetti@athonet.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = "=0.2.0-alpha.6"
hyper = { version = "=0.13.0-alpha.4", features = ["unstable-stream"] }
hyper-tls = "=0.4.0-alpha.4"
mysql_async = "=0.21.0-alpha.4"
ingress_intel_rs = { git = "https://github.com/nappa85/ingress-intel-rs.git" }
once_cell = "1.2"
log = "0.4"
env_logger = "0.7"
