[package]
name = "portal-updater"
version = "0.1.2"
authors = ["Marco Napetti <marco.napetti@athonet.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2", features = ["full"] }
hyper = { version = "0.13", features = ["stream"] }
hyper-tls = "0.4"
mysql_async = "0.21"
ingress_intel_rs = { git = "https://github.com/nappa85/ingress-intel-rs.git" }
once_cell = "1.3"
log = "0.4"
env_logger = "0.7"
