[package]
name = "portal-updater"
version = "0.2.0"
authors = ["Marco Napetti <marco.napetti@athonet.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2", features = ["macros"] }
mysql_async = "0.25"
ingress_intel_rs = { git = "https://github.com/nappa85/ingress-intel-rs.git" }
once_cell = "1.4"
log = "0.4"
env_logger = "0.8"
